### PR TITLE
add some functionality

### PR DESCRIPTION
**Pull request by haxi0**
PLEASE ADD SDWEBIMAGESWIFTUI INTO DEPENDENCY SO THAT IT WORKS!!!

### CODE REVIEW

**Comment by llsc12** [comment]
wait up

**Comment by llsc12** [comment]
lemme get xcode up and ill do a proper check

**Comment by sourcelocation** [comment]
that was a joke :skull:

**Comment by llsc12** [comment]
whar

**Comment by sourcelocation** [comment]
No.

**Pull request closed without merging**
